Repository imAsparky/django-cookiecutter, pull requests merged in 2023-05, with the labels that each got.

#559 fix(deps): Update Django to 4.2.1 #558
  {{cookiecutter.git_project_name}}/config/requirements/base.txt
Labels: bug, dependencies

#560 docs(deps): Revert to sphinx 6.2.1 #557
  docs/requirements.txt
Labels: documentation

#563 chore(deps): Revert relekang to @master #562
  .github/workflows/semantic_release.yaml
Labels: chore

#556 Update how-to-quickstart.rst
  docs/source/how-tos/how-to-quickstart.rst
Labels: documentation

#564 chore(deps): Update pytest-xdist from 3.2.1 to 3.3.1
  {{cookiecutter.git_project_name}}/config/requirements/test.txt
Labels: chore, dependencies
